app: challenge-app
service: challenge-app
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs20.x

functions:
  getReviews:
    handler: src/getReviews.handler
    timeout: 900
    events:
      - schedule: rate(10 minutes)
  getCompanyReviews:
    handler: src/getCompanyReviews.handler
    events:
      - httpApi:
          path: /reviews/company/{companyId}
          method: get
  getAll:
    handler: src/getAll.handler
    events:
      - httpApi:
          path: /all
          method: get
          timeout: 30
  getReviewById:
    handler: src/getReviewById.handler
    events:
      - httpApi:
          path: /reviews/{reviewId}
          method: get
  getReviewerById:
    handler: src/getReviewerById.handler
    events:
      - httpApi:
          path: /reviewers/{reviewerId}
          method: get

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-dotenv-plugin

package:
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'