import { z } from "zod";

export const scrapeSchema = z.array(
  z.object({
    url: z.string(),
    searchString: z.string(),
    isAdvertisement: z.boolean(),
    title: z.string(),
    categoryName: z.string(),
    address: z.string(),
    neighborhood: z.string(),
    street: z.string(),
    city: z.string(),
    postalCode: z.string(),
    state: z.string(),
    countryCode: z.string(),
    website: z.string(),
    phone: z.string(),
    phoneUnformatted: z.string(),
    claimThisBusiness: z.boolean(),
    location: z.object({ lat: z.number(), lng: z.number() }),
    plusCode: z.string(),
    menu: z.string(),
    totalScore: z.number(),
    permanentlyClosed: z.boolean(),
    temporarilyClosed: z.boolean(),
    placeId: z.string(),
    categories: z.array(z.string()),
    cid: z.string(),
    reviewsCount: z.number(),
    reviewsDistribution: z.object({
      oneStar: z.number(),
      twoStar: z.number(),
      threeStar: z.number(),
      fourStar: z.number(),
      fiveStar: z.number(),
    }),
    imagesCount: z.number(),
    imageCategories: z.array(z.string()),
    scrapedAt: z.string(),
    reserveTableUrl: z.null(),
    googleFoodUrl: z.string(),
    reviews: z.array(
      z.object({
        name: z.string(),
        text: z.string().nullish(),
        textTranslated: z.string().nullish(),
        publishAt: z.string(),
        publishedAtDate: z.string(),
        likesCount: z.number(),
        reviewId: z.string().nullish(),
        reviewUrl: z.string().nullish(),
        reviewerId: z.string().nullish(),
        reviewerUrl: z.string().nullish(),
        reviewerPhotoUrl: z.string().nullish(),
        reviewerNumberOfReviews: z.number().nullish(),
        isLocalGuide: z.boolean(),
        stars: z.number(),
        rating: z.null(),
        responseFromOwnerDate: z.string().nullish(),
        responseFromOwnerText: z.string().nullish(),
        reviewImageUrls: z.array(z.unknown()),
        reviewContext: z.object({}),
        reviewDetailedRating: z.object({}),
      })
    ),
  })
);

export const minimalScrapeSchema = z.array(
  z.object({
    url: z.string(),
    searchString: z.string(),
    searchPageUrl: z.string().nullish(),
    searchPageLoadedUrl: z.string().nullish(),
    isAdvertisement: z.boolean().nullish(),
    title: z.string(),
    description: z.null(),
    price: z.null(),
    categoryName: z.string(),
    address: z.string(),
    neighborhood: z.string(),
    street: z.string(),
    city: z.string(),
    postalCode: z.string(),
    state: z.string(),
    countryCode: z.string(),
    website: z.string(),
    phone: z.string(),
    phoneUnformatted: z.string(),
    location: z.object({ lat: z.number(), lng: z.number() }),
    plusCode: z.string(),
    menu: z.string(),
    totalScore: z.number(),
    placeId: z.string(),
    categories: z.array(z.string()),
    cid: z.string(),
    reviewsCount: z.number(),
    reviewsDistribution: z.object({
      oneStar: z.number(),
      twoStar: z.number(),
      threeStar: z.number(),
      fourStar: z.number(),
      fiveStar: z.number(),
    }),
    imagesCount: z.number(),
    imageCategories: z.array(z.string()),
    scrapedAt: z.string(),
    googleFoodUrl: z.string().nullish(),
  })
);
